RESEARCH_BASE_DIR = "C:/MLDATA"
RESEARCH_BASE_FILE = RESEARCH_BASE_DIR + "/colorSystem.bin"
SUBPROCESS_ARGV = RESEARCH_BASE_DIR + "/subprocData.bin"
RECOMMAND_BASE_FILE = RESEARCH_BASE_DIR + "/recommand.bin"